
export enum LiveStatus {
  DISCONNECTED = 'disconnected',
  CONNECTING = 'connecting',
  CONNECTED = 'connected',
  ERROR = 'error',
}

export interface AudioVolumeState {
  inputVolume: number;
  outputVolume: number;
}

export interface VisualizerData {
  inputData: Uint8Array;
  outputData: Uint8Array;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  isFinal?: boolean;
}

// Allow string for dynamic scenarios generated by AI
export type ScenarioType = 'general' | 'work' | 'relationship' | 'interview' | string;

export interface Scenario {
  id: ScenarioType;
  label: string;
  prompt: string;
}

export type AppView = 'call' | 'recommendations' | 'profile';

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  avatarUrl?: string;
}

export type Tone = 'neutral' | 'warm' | 'anxious' | 'encouraging' | 'assertive';
