
export enum LiveStatus {
  DISCONNECTED = 'disconnected',
  RESEARCHING = 'researching',
  CONNECTING = 'connecting',
  CONNECTED = 'connected',
  ERROR = 'error',
}

export interface AudioVolumeState {
  inputVolume: number;
  outputVolume: number;
}

export interface VisualizerData {
  inputData: Uint8Array;
  outputData: Uint8Array;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  isFinal?: boolean;
}

// Allow string for dynamic scenarios generated by AI
export type ScenarioType = 'general' | 'work' | 'relationship' | 'interview' | string;

export interface Scenario {
  id: ScenarioType;
  label: string;
  prompt: string;
}

export interface Agent {
  id: string;
  name: string;
  role: string;
  description: string;
  voiceName: string;
  stylePrompt: string;
  hiddenDirectives: string[]; // Specific instructions for the model (e.g., "Interrupt if...")
  evaluationCriteria: string[]; // What this agent cares about most in the report
  color: string;
}

export interface KnowledgeSnippet {
  id: string;
  title: string;
  content: string;
  tags: string[];
}

export interface KnowledgeAsset {
  id: string;
  name: string;
  type: 'text'; // Future: 'pdf' | 'doc'
  content: string;
  isActive: boolean;
}

export type AppView = 'call' | 'recommendations' | 'profile' | 'context';

export type CoachingStyle = 'gentle' | 'direct' | 'analytical';

export type Language = 'en' | 'th';

export interface UserPreferences {
  coachingStyle: CoachingStyle;
  focusAreas: string[];
  communicationGoal: string;
}

export interface SessionAnalysis {
  id: string;
  timestamp: number;
  clarityScore: number; // 1-10
  confidenceScore: number; // 1-10
  empathyScore: number; // 1-10
  feedback: string;
  topic: string;
  agentId?: string; // Track who gave the feedback
}

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  avatarUrl?: string;
  preferences?: UserPreferences;
  history: SessionAnalysis[];
  knowledgeAssets?: KnowledgeAsset[];
}

export type Tone = 'neutral' | 'warm' | 'anxious' | 'encouraging' | 'assertive';
